const grid=document.getElementById('grid'),empty=document.getElementById('empty');const scope=document.getElementById('scope'),orgFilter=document.getElementById('org'),deadline=document.getElementById('deadline');const exportBtn=document.getElementById('exportCsv'),stamp=document.getElementById('lastUpdated');
function setStamp(){stamp.textContent='Last Updated: '+new Date().toLocaleString();}
function queryDataUrl(){const p=new URLSearchParams(location.search);return p.get('data')||"";}
async function loadData(){const isHttp=location.protocol.startsWith('http');const override=window.DATA_URL||queryDataUrl();if(isHttp){const url=override||'./data/grants.json';try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw 0;return await r.json()}catch(e){return window.SNAPSHOT||[]}}return window.SNAPSHOT||[]}
function daysUntil(s){if(!s||String(s).toLowerCase().includes('rolling'))return 9999;const t=new Date(s+'T23:59:59');return Math.ceil((t-new Date())/86400000)}
function filterFn(){const sc=scope.value,ov=orgFilter.value,dv=deadline.value;return g=>{const isUSA=g.region==='USA';const scopeOk=(sc==='All')||(sc==='USA'&&isUSA)||(sc==='INTL'&&!isUSA);const orgOk=(ov==='All')||(g.org===ov);const dOk=(dv==='Any')?true:(()=>{const d=daysUntil(g.deadline||'');return d>=0&&d<=parseInt(dv)})();return scopeOk&&orgOk&&dOk}}
function host(u){try{return new URL(u).host.replace('www.','')}catch(e){return ''}}
function render(list){const arr=list.filter(filterFn());grid.innerHTML='';if(!arr.length){empty.style.display='block';return}empty.style.display='none';arr.forEach(g=>{const el=document.createElement('div');el.className='card';el.innerHTML=`<h3 class="title">${g.title}</h3><div class="meta"><strong>Organization:</strong> ${g.org}</div><div class="meta"><strong>Deadline:</strong> ${g.deadline||'Rolling'} • <strong>Amount:</strong> ${g.amount}</div><div class="chips"><span class="chip">${g.region}</span> ${host(g.apply_url)?`<span class="chip">${host(g.apply_url)}</span>`:''}</div><div class="actions"><a class="btn" href="${g.apply_url}" target="_blank" rel="noopener">Apply Now</a></div>`;grid.appendChild(el)})}
function exportCSV(list){const arr=list.filter(filterFn()),h=["Title","Organization","Deadline","Amount","Region","Apply URL","Exported At"];const ts=new Date().toLocaleString();let csv=h.join(",")+"\n";arr.forEach(g=>{csv+=[g.title,g.org,g.deadline||'Rolling',g.amount,g.region,g.apply_url,ts].map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(",")+"\n"});const blob=new Blob([csv],{type:"text/csv;charset=utf-8;"}),url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download="YOPAC_Grants_Export.csv";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
(async()=>{setStamp();const data=await loadData();Array.from(new Set(data.map(d=>d.org))).sort().forEach(o=>{const opt=document.createElement('option');opt.value=o;opt.textContent=o;orgFilter.appendChild(opt)});const rerender=()=>render(data);scope.addEventListener('change',rerender);orgFilter.addEventListener('change',rerender);deadline.addEventListener('change',rerender);exportBtn.addEventListener('click',()=>exportCSV(data));render(data)})();